# jekyll settings
include:
  - "_pages"

exclude:
  - "*.sh"
  - .jekyll-cache
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "node_modules"
  - "notes.txt"
  - "package-lock.json"
  - "package.json"
  - "README.md"

markdown: kramdown

kramdown:
  auto_ids: true
  parse_block_html: true


# site settings
sitename: "new.qmedia.de"
# url: "https://www.new.qmedia.de"
url: "https://test-kirbelots.bitbucket.io"
baseurl: ""
lang: "de_DE"
og_image: "https://test-kirbelots.bitbucket.io/assets/images/qmedia-logo.png"
og_image_width: 600
og_image_height: 600
